### ISSUE TITLE
ImportError : cannot import name 'WebServiceAction' from 'pyscada.webservice.models

### ISSUE THREAD

**Issue by vincent-inviseo** [clavay/PyScada-WebService#7]
during migrations applying a error occur for this plugin.

![Capture d’écran du 2024-02-14 10-45-34](https://github.com/clavay/PyScada-WebService/assets/132346203/15500561-c06f-4320-afe3-f779f12fff55)

**Comment by clavay** [comment]
There is no `admin.py` file on this plugin now, please update to the last version.
